services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "http://supabase:8000"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZmZ5cGtlcG1tbW9sbW9lZ3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTQzNTM1MjksImV4cCI6MjAwOTkyOTUyOX0.4XG-W6lV8yAgwD8wCqYR0dJ7KZKhY9E9V9n7y9X9X9I"
    depends_on:
      - supabase

  supabase:
    image: supabase/postgres:15.1.0.89
    environment:
      POSTGRES_PASSWORD: "senhaSegura123"
      JWT_SECRET: "segredoSuperSecreto456"
    ports:
      - "5432:5432"
      - "8000:8000"
      - "3001:3000"  # Supabase Studio
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data: